version: '3.8'
services:
  vm-s-time:
    container_name: ubuntu-vm-s-time
    build: docker/ubuntu
    volumes:
      # - ./showtime_source_api:/root/project
      # - ./docker/ubuntu/application.properties:/root/project/src/main/resources/application.properties
      - ./m2:/root/.m2
    working_dir: /root/project
    ports:
      - "89:8080"
  db:
    container_name: show_time_db
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev_showtime
    ports:
      - '5432:5432'
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
  pgadmin:
    build: docker/pgadmin
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: showtime@dev.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
volumes:
    local_pgdata:
    pgadmin-data: