name: workflow production without sonarqube test
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy prod testless'
        required: true
        default: 'latest'
jobs:
  prod-deploy:
    environment: production
    runs-on: ubuntu-latest
    container:
      image: kevinpsirius/javadeployspring:v2
      env:
        sshKey: ${{ secrets.SSH_KEY }}
        envDeploymentProd: ${{ secrets.ENVDEPLOYMENTPRODUCTION }}
        applicationProdProperties: ${{ secrets.APPLICATION_PROD_PROPERTIES }}
        liquibaseProdProperties: ${{ secrets.LIQUIBASE_PROD_PROPERTIES }}
    steps:
      - name: Generate the updated target directory to push on production
        run: |
          git clone https://github.com/JAKY99/showtime_API.git
          rm showtime_API/src/main/resources/*.properties
          touch showtime_API/src/main/resources/application.properties && echo "$applicationProdProperties" >> showtime_API/src/main/resources/application.properties
          touch showtime_API/src/main/resources/liquibase.properties && echo "$liquibaseProdProperties" >> showtime_API/src/main/resources/liquibase.properties
          touch showtime_API/.env && echo "$envDeploymentProd" >> showtime_API/.env
          cd showtime_API && mvn clean install -DskipTests
          touch /var/www/html/mypckey.pem &&  chmod 600 /var/www/html/mypckey.pem && echo "$sshKey" >> /var/www/html/mypckey.pem
          cd /var/www/html/playbook && ansible-playbook deploy-prod-api-backend.yml -e "ansible_ssh_timeout=180"
