name: workflow production without sonarqube test
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy prod testless'
        required: true
        default: 'latest'
jobs:
  prod-deploy:
    needs: sonarqube-test
    environment: production
    runs-on: ubuntu-latest
    container:
      image: kevinpsirius/javadeployspring:v2
      env:
        sshKey: ${{ secrets.SSH_KEY }}
        envDeploymentProd: ${{ secrets.ENVDEPLOYMENTPRODUCTION }}
    steps:
      - name: Generate the updated target directory to push on production
        run: |
          git clone https://github.com/JAKY99/showtime_API.git
          rm showtime_API/src/main/resources/liquibase.properties && mv showtime_API/src/main/resources/liquibase.prod.properties showtime_API/src/main/resources/liquibase.properties
          rm showtime_API/src/main/resources/application.properties && mv showtime_API/src/main/resources/application.prod.properties showtime_API/src/main/resources/application.properties
          touch showtime_API/.env && echo "$envDeploymentProd" >> showtime_API/.env
          cd showtime_API && mvn clean install -DskipTests
          touch /var/www/html/mypckey.pem &&  chmod 600 /var/www/html/mypckey.pem && echo "$sshKey" >> /var/www/html/mypckey.pem
          cd /var/www/html/playbook && ansible-playbook deploy-prod-api-backend.yml -e "ansible_ssh_timeout=180"
