name: workflow hotfix staging (testless)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Deploy testless staging'
        required: true
        default: 'latest'
jobs:
  staging-deploy:
    environment: staging
    runs-on: ubuntu-latest
    container:
      image: kevinpsirius/javadeployspring:v2
      env:
        sshKey: ${{ secrets.SSH_KEY }}
        envDeploymentStaging: ${{ secrets.ENVDEPLOYMENTSTAGING }}
        postgresPassword: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Generate the updated target directory to push on staging
        run: |
          git clone https://github.com/JAKY99/showtime_API.git
          git config --global --add safe.directory /__w/showtime_API/showtime_API
          cd showtime_API && git checkout develop && cd ..
          rm showtime_API/src/main/resources/liquibase.properties 
          mv showtime_API/src/main/resources/liquibase.dev.properties showtime_API/src/main/resources/liquibase.properties 
          rm showtime_API/src/main/resources/application.properties 
          mv showtime_API/src/main/resources/application.dev.properties showtime_API/src/main/resources/application.properties
          touch showtime_API/src/main/resources/.env  && echo "$envDeploymentStaging" >> showtime_API/src/main/resources/.env 
          sed -i "s/password=postgres/password=$postgresPassword/g" showtime_API/src/main/resources/liquibase.properties 
          cd showtime_API && mvn dependency:purge-local-repository &&  mvn clean install -DskipTests --update-snapshots
          touch /var/www/html/mypckey.pem && chmod 600 /var/www/html/mypckey.pem && echo "$sshKey" >> /var/www/html/mypckey.pem
          cd playbook  && ansible-playbook deploy-dev-api-backend.yml -e "ansible_ssh_timeout=180"
